"""add name to BakedGood

Revision ID: 01038a383edc
Revises: c71d8e9968af
Create Date: 2023-09-08 03:52:32.514466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01038a383edc'
down_revision = 'c71d8e9968af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baked_goods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baked_goods', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
